#!/usr/bin/env bash

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

OFFBOARD_LOG_DISABLE="${OFFBOARD_LOG_DISABLE:-false}"
if [ "$OFFBOARD_LOG_DISABLE" != "true" ] && [ "${OFFBOARD_LOG_ACTIVE:-false}" != "true" ]; then
  OFFBOARD_LOG_ROOT="${OFFBOARD_LOG_ROOT:-$REPO_DIR/results/offboard}"
  OFFBOARD_RUN_ID="${OFFBOARD_RUN_ID:-$(date +%Y%m%d_%H%M%S)}"
  OFFBOARD_LOG_DIR="$OFFBOARD_LOG_ROOT/$OFFBOARD_RUN_ID"
  OFFBOARD_LOG_FILE="$OFFBOARD_LOG_DIR/offboard.log"
  mkdir -p "$OFFBOARD_LOG_DIR"
  ln -sfn "$OFFBOARD_LOG_DIR" "$OFFBOARD_LOG_ROOT/latest"
  export OFFBOARD_LOG_ACTIVE=true
  export OFFBOARD_LOG_DIR
  export OFFBOARD_LOG_FILE

  echo "Saving Offboard task log:"
  echo "  directory: $OFFBOARD_LOG_DIR"
  echo "  file:      $OFFBOARD_LOG_FILE"
  echo "  latest:    $OFFBOARD_LOG_ROOT/latest"
  echo

  exec > >(tee -a "$OFFBOARD_LOG_FILE") 2>&1
  echo "===== OFFBOARD TASK LOG START $(date --iso-8601=seconds) ====="
  echo "cwd=$PWD"
  echo "command=$0 $*"
  echo
fi

cat <<'EOF'
Outdoor MAVROS Offboard low-speed task.

Default behavior:
  - expects MAVROS already connected to Pixhawk
  - expects RC transmitter ready for MANUAL/disarm/kill takeover
  - expects the vehicle to be manually armed before the sequence starts
  - requests OFFBOARD from the script
  - drives: forward 1s, stop, backward 1s, stop, left/right small turns
  - aborts if mode leaves OFFBOARD or the vehicle disarms
EOF

TEST_SURFACE="ground"
MODE_CHANGE_ON_START="true"
ARM_ON_START="false"
REQUIRE_ARMED_BEFORE_MODE_CHANGE="true"
MODE_REQUEST_RETRY_SEC="${MODE_REQUEST_RETRY_SEC:-2.0}"
ARM_REQUEST_RETRY_SEC="${ARM_REQUEST_RETRY_SEC:-2.0}"
DISARM_ON_FINISH="true"
REQUIRE_CONNECTED="true"
REQUIRE_OFFBOARD_MODE="true"
REQUIRE_ARMED="true"
ABORT_ON_MODE_EXIT="true"
ABORT_ON_DISARM="true"
ABORT_ON_ARM_REJECTED="true"
MAX_WAIT_FOR_READY_SEC="${MAX_WAIT_FOR_READY_SEC:-30}"
COMMAND_RATE_HZ="${COMMAND_RATE_HZ:-20}"
PUBLISH_UNSTAMPED_CMD_VEL="${PUBLISH_UNSTAMPED_CMD_VEL:-true}"
WARMUP_SEC="${WARMUP_SEC:-2.0}"
STOP_SEC="${STOP_SEC:-1.0}"
FORWARD_SEC="${FORWARD_SEC:-1.0}"
BACKWARD_SEC="${BACKWARD_SEC:-1.0}"
TURN_SEC="${TURN_SEC:-0.5}"
FINAL_STOP_SEC="${FINAL_STOP_SEC:-2.0}"
LINEAR_SPEED_MPS="${LINEAR_SPEED_MPS:-0.05}"
TURN_YAW_RATE_RADPS="${TURN_YAW_RATE_RADPS:-0.12}"
MAX_LINEAR_SPEED_MPS="${MAX_LINEAR_SPEED_MPS:-0.12}"
MAX_YAW_RATE_RADPS="${MAX_YAW_RATE_RADPS:-0.25}"

cat <<EOF
Effective outdoor settings:
  TEST_SURFACE=$TEST_SURFACE
  MODE_CHANGE_ON_START=$MODE_CHANGE_ON_START
  ARM_ON_START=$ARM_ON_START
  REQUIRE_ARMED_BEFORE_MODE_CHANGE=$REQUIRE_ARMED_BEFORE_MODE_CHANGE
  MODE_REQUEST_RETRY_SEC=$MODE_REQUEST_RETRY_SEC
  PUBLISH_UNSTAMPED_CMD_VEL=$PUBLISH_UNSTAMPED_CMD_VEL
  LINEAR_SPEED_MPS=$LINEAR_SPEED_MPS
  TURN_YAW_RATE_RADPS=$TURN_YAW_RATE_RADPS
  MAX_WAIT_FOR_READY_SEC=$MAX_WAIT_FOR_READY_SEC
EOF

exec env \
  TEST_SURFACE="$TEST_SURFACE" \
  MODE_CHANGE_ON_START="$MODE_CHANGE_ON_START" \
  ARM_ON_START="$ARM_ON_START" \
  REQUIRE_ARMED_BEFORE_MODE_CHANGE="$REQUIRE_ARMED_BEFORE_MODE_CHANGE" \
  MODE_REQUEST_RETRY_SEC="$MODE_REQUEST_RETRY_SEC" \
  ARM_REQUEST_RETRY_SEC="$ARM_REQUEST_RETRY_SEC" \
  DISARM_ON_FINISH="$DISARM_ON_FINISH" \
  REQUIRE_CONNECTED="$REQUIRE_CONNECTED" \
  REQUIRE_OFFBOARD_MODE="$REQUIRE_OFFBOARD_MODE" \
  REQUIRE_ARMED="$REQUIRE_ARMED" \
  ABORT_ON_MODE_EXIT="$ABORT_ON_MODE_EXIT" \
  ABORT_ON_DISARM="$ABORT_ON_DISARM" \
  ABORT_ON_ARM_REJECTED="$ABORT_ON_ARM_REJECTED" \
  MAX_WAIT_FOR_READY_SEC="$MAX_WAIT_FOR_READY_SEC" \
  COMMAND_RATE_HZ="$COMMAND_RATE_HZ" \
  PUBLISH_UNSTAMPED_CMD_VEL="$PUBLISH_UNSTAMPED_CMD_VEL" \
  WARMUP_SEC="$WARMUP_SEC" \
  STOP_SEC="$STOP_SEC" \
  FORWARD_SEC="$FORWARD_SEC" \
  BACKWARD_SEC="$BACKWARD_SEC" \
  TURN_SEC="$TURN_SEC" \
  FINAL_STOP_SEC="$FINAL_STOP_SEC" \
  LINEAR_SPEED_MPS="$LINEAR_SPEED_MPS" \
  TURN_YAW_RATE_RADPS="$TURN_YAW_RATE_RADPS" \
  MAX_LINEAR_SPEED_MPS="$MAX_LINEAR_SPEED_MPS" \
  MAX_YAW_RATE_RADPS="$MAX_YAW_RATE_RADPS" \
  CONFIRM_QGC_DISARM_READY="${CONFIRM_QGC_DISARM_READY:-false}" \
  CONFIRM_PHYSICAL_POWER_CUTOFF_READY="${CONFIRM_PHYSICAL_POWER_CUTOFF_READY:-false}" \
  AUTO_RESTORE_OUTPUT_MAPPING="${AUTO_RESTORE_OUTPUT_MAPPING:-true}" \
  "$REPO_DIR/scripts/run_real_rover_mavros_offboard_smoke.sh"
