#!/usr/bin/env bash

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

export MISSION_PROFILE=left_uturn
export FORWARD_DISTANCE_M="${FORWARD_DISTANCE_M:-5.0}"
export LINEAR_SPEED_MPS="${LINEAR_SPEED_MPS:-0.06}"
export TERMINAL_SPEED_MPS="${TERMINAL_SPEED_MPS:-0.035}"
export TURN_ANGLE_DEG="${TURN_ANGLE_DEG:-180.0}"
export TURN_TOLERANCE_DEG="${TURN_TOLERANCE_DEG:-8.0}"
export TURN_FORWARD_SPEED_MPS="${TURN_FORWARD_SPEED_MPS:-0.05}"
export TURN_LATERAL_SPEED_MPS="${TURN_LATERAL_SPEED_MPS:-0.04}"
export TURN_MAX_SEC="${TURN_MAX_SEC:-45.0}"
export TURN_COMPLETION_HOLD_SEC="${TURN_COMPLETION_HOLD_SEC:-0.30}"
export TURN_STALL_WINDOW_SEC="${TURN_STALL_WINDOW_SEC:-8.0}"
export TURN_STALL_MIN_PROGRESS_DEG="${TURN_STALL_MIN_PROGRESS_DEG:-5.0}"
export TURN_CLEARANCE_RADIUS_M="${TURN_CLEARANCE_RADIUS_M:-3.5}"
export TURN_RADIUS_M="${TURN_RADIUS_M:-3.2}"

exec "$REPO_DIR/scripts/run_orin2_outdoor_forward_5m.sh" "$@"
